name: JANDROID

on:
 push:
  branches:
   - '**'

# trigger workflow on file change
#on:
# push:
#  paths:
#   - 'version.txt'

# if: ${{ false }}

jobs:

# linux ----------------------------------------------------------------
 jalinux:
  name: JANROID
  runs-on: ubuntu-20.04
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v2

   - name: Build JANDROID
     run: |
      cd ~/
      wget https://github.com/jsoftware/jsource/releases/download/build/androidlibs.zip
      unzip androidlibs.zip
      cd -
      cp ~/libs/arm64-v8a/* libs/arm64-v8a/.
      cp ~/libs/armeabi/* libs/armeabi/.
      cp ~/libs/armeabi-v7a/* libs/armeabi-v7a/.
      cp ~/libs/x86/* libs/x86/.
      ./gradlew build
      ./gradlew assemble

   - name: Sign apk
     id: sign_apk
     uses: r0adkll/sign-android-release@v1
     with:
       releaseDirectory: build/outputs/apk/release
       signingKeyBase64: ${{ secrets.SIGNING_KEY }}
       alias: ${{ secrets.SIGNING_KEY_ALIAS }}
       keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
       keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
 
   - name: Upload
     uses: actions/upload-artifact@v2
     with:
       name: Build Artifacts
       path: ${{steps.sign_apk.outputs.signedReleaseFile}}
